# Generated by Django 4.0 on 2022-02-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailsForMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email пользователя, которому нужно отправлять сообщения о заказах', max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name_plural': ' Почта для уведомлений',
            },
        ),
    ]
