# Generated by Django 4.0 on 2022-02-27 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_time_call_to_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_call_to_api',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя дата и время обращения к API'),
        ),
    ]
