# Generated by Django 4.0 on 2022-02-13 10:53

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название категории', max_length=40, unique=True, verbose_name='Заголовок')),
                ('image', models.ImageField(help_text='Прикрепите картинку к категории', upload_to='categoryes/', verbose_name='Картинка категории')),
                ('title_image', models.ImageField(help_text='Эта картинка показывается на странице категории в заголовке', upload_to='categoryes_preview/', verbose_name='Заголовочная картинка')),
            ],
            options={
                'verbose_name_plural': '    Категории',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Характеристика товара, название', max_length=100, verbose_name='Характеристика')),
                ('dimension', models.CharField(blank=True, help_text='Вы можете указать измерение характеристики.', max_length=40, null=True, verbose_name='Измерение')),
            ],
            options={
                'verbose_name_plural': '  Характерристики товара',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('state', models.TextField(choices=[('Корзина', 'shopping_cart'), ('Заказ', 'order'), ('Выполнен', 'order_complete')], default='Корзина', verbose_name='Статус заказа')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='shoplists', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': '      Заказы пользователей',
            },
        ),
        migrations.CreateModel(
            name='PreviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Прикрепите баннер, который будет высвечиваться на главной странице', upload_to='previews/', verbose_name='Баннер главной страницы')),
                ('first', models.BooleanField(help_text='Сделать этот баннер первым', verbose_name='Первый баннер')),
            ],
            options={
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.TextField(blank=True, help_text='Через "&&" укажите комплект. Пример: "Предмет&&Ложка&&Вилка&&Тарелька"', verbose_name='Комплектация')),
                ('title', models.CharField(help_text='Укажите название товара', max_length=40, unique=True, verbose_name='Название')),
                ('price', models.FloatField(help_text='Укажите цену товара', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Цена')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Вы можете указать описание продукта', verbose_name='Описание')),
                ('preview_image', models.ImageField(default='product.jpeg', help_text='Прикрепите превью картинку к товару (показывается в карточке)', upload_to='product_preview_image/', verbose_name='Превью картинка продукта')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name_plural': '      Товары',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название подкатегории', max_length=40, unique=True, verbose_name='Заголовок')),
                ('title_image', models.ImageField(help_text='Эта картинка показывается на странице подкатегории в заголовке', upload_to='subcategoryes_preview/', verbose_name='Заголовочная картинка')),
                ('image', models.ImageField(help_text='Прикрепите картинку к подкатегории', upload_to='subcategoryes/', verbose_name='Картинка')),
                ('category', models.ForeignKey(help_text='Укажите к какой категории относится подкатегория', on_delete=django.db.models.deletion.CASCADE, related_name='in_subcategories', to='online_store.category', verbose_name='К какой категории относится')),
                ('characteristics', models.ManyToManyField(help_text='Укажите характеристики подкатегории', related_name='in_subcategories', to='online_store.Characteristic', verbose_name='Характеристики')),
            ],
            options={
                'verbose_name_plural': '   Подкатегории',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='QuantityCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(help_text='Укажите значение', max_length=50, verbose_name='Значение')),
                ('characteristic', models.ForeignKey(help_text='Укажите к какой характеристике количество', on_delete=django.db.models.deletion.CASCADE, related_name='in_quantity_characteristics', to='online_store.characteristic', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name_plural': ' Кол-во характеристики',
                'ordering': ('characteristic',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Прикрепите картинку к товару', upload_to='product_image/', verbose_name='Картинка продукта')),
                ('first', models.BooleanField(help_text='Сделать эту картинку первой', verbose_name='Первая картинка')),
                ('product', models.ForeignKey(help_text='Укажите товар к которому прикрепить картинку', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='online_store.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name_plural': '     Картинки товаров',
                'ordering': ('product', 'first'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.ManyToManyField(help_text='Укажите характеристики продукта. Все характеристики подкатегории должны быть указаны у этого продукта!', related_name='in_products', to='online_store.QuantityCharacteristics', verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(help_text='Укажите к какой категории относится товар', on_delete=django.db.models.deletion.CASCADE, related_name='in_products', to='online_store.subcategory', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Укажите количество заказываемого товара', verbose_name='Количество товара')),
                ('order', models.ForeignKey(help_text='К какому заказу относится', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='online_store.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(help_text='Выберите рецепт', on_delete=django.db.models.deletion.CASCADE, related_name='in_orders', to='online_store.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name_plural': '       Составляющие заказов',
            },
        ),
        migrations.AddConstraint(
            model_name='characteristic',
            constraint=models.UniqueConstraint(fields=('dimension', 'title'), name='unique dimension'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique product'),
        ),
    ]
