# Generated by Django 4.0 on 2022-02-26 11:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_emailsformessages'),
        ('online_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '       Заказы пользователей'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': '      Составляющие заказов'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated',
        ),
        migrations.AddField(
            model_name='order',
            name='date_state_complete',
            field=models.DateField(default=datetime.date.today, help_text='По умолчанию - дата создания записи. (Если не был переведён в статус "Получен")', verbose_name='Дата установки статуса "Получен"'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_state_in_delivery',
            field=models.DateField(default=datetime.date.today, help_text='По умолчанию - дата создания записи. (Если не был переведён в статус "Отправлен")', verbose_name='Дата установки статуса "Отправлен"'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_state_in_processing',
            field=models.DateField(default=datetime.date.today, help_text='По умолчанию - дата создания записи. (Если не был переведён в статус "В обработке")', verbose_name='Дата установки статуса "В обработке"'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.TextField(choices=[('Корзина', 'shopping_cart'), ('В обработке', 'in_processing'), ('Отправлен', 'in_delivery'), ('Получен', 'order_complete')], default='Корзина', verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='in_orders', to='users.user', verbose_name='Пользователь'),
        ),
    ]
