# Generated by Django 4.0 on 2022-02-13 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_emailsformessages'),
        ('online_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '       Заказы пользователей'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': '      Составляющие заказов'},
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='in_orders', to='users.user', verbose_name='Пользователь'),
        ),
    ]
