# Generated by Django 4.0 on 2022-02-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0003_remove_subcategory_characteristics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Укажите название товара', max_length=70, unique=True, verbose_name='Название'),
        ),
    ]
