# Generated by Django 4.0 on 2022-02-26 12:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0004_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_state_shopping_list',
            field=models.DateField(default=datetime.date.today, help_text='По умолчанию - дата создания записи', verbose_name='Дата установки статуса "Корзина"'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(help_text='Укажите к какой категории относится товар', on_delete=django.db.models.deletion.CASCADE, related_name='in_products', to='online_store.subcategory', verbose_name='Подкатегория'),
        ),
    ]
